# Generated by Django 4.2.11 on 2024-03-14 18:10

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField(max_length=1000)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.CharField(blank=True, max_length=10000)),
                ('queryn', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(max_length=100000)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('likes', models.ManyToManyField(related_name='post_query', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
